### ISSUE TITLE
Typos in google / ftc-object-detection / training / README.md

### ISSUE THREAD

**Issue by jrasor** [google/ftc-object-detection#12]
Full url to that README.md: https://github.com/google/ftc-object-detection/tree/master/training.

> bazel run -c opt tensorflow/contrib/lite/toco:toco -- \
>     --input_file=[PATH TO THIS REPO]/training/models/sample_mobilenet_v1_0.5_ssd_quantized/tflite/tflite_graph.pb \
>     --output_file=[PATH TO THIS REPO]/training/models/sample_mobilenet_v1_0.5_ssd_quantized/tflite/detect.tflite \
>     --input_shapes=1,300,300,3 \
>     --input_arrays='normalized_input_image_tenor' \
>     --
ouptut_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \
>     --inference_type=QUANTIZED_UINT8 \
>     --mean_values=128 \
>     --std_values=128 \
>     --change_concat_input_ranges=false \
>     --allow_custom_ops

Look in the middle.

**tenor** should be **tensor.**
**ouptut** should be **output**.

**Comment by lizlooney** [comment]
Thanks for the issue report!
